# -*- coding: utf-8 -*-
"""Task 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V6Nvmxuwr0PhNxAMTYxJ8sl_wBuGB3RW
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

sns.set(style="whitegrid")
plt.style.use("seaborn-v0_8")

def initial_audit(df):
    print("SHAPE ")
    print(df.shape)

    print("\n DATA TYPES ")
    print(df.dtypes)

    print("\n MISSING VALUES ")
    print(df.isnull().sum())

    print("\n STATISTICS (NUMERIC) ")
    print(df.describe().T)

    print("\n STATISTICS (CATEGORICAL)")
    print(df.describe(include="object").T)

df = sns.load_dataset("titanic")
initial_audit(df)

plt.figure(figsize=(10,5))
sns.heatmap(df.isna(), cbar=False, cmap="magma")
plt.title("Missing Value Map")
plt.show()

def numeric_distributions(df):
    numeric_cols = df.select_dtypes(include=np.number).columns

    for col in numeric_cols:
        plt.figure(figsize=(8,4))
        sns.histplot(df[col], kde=True)
        plt.title(f"Distribution: {col}")
        plt.show()

def outlier_report(df):
    numeric = df.select_dtypes(include=np.number).columns
    report = {}

    for col in numeric:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        outliers = df[(df[col] < lower) | (df[col] > upper)][col].count()
        report[col] = outliers

    return pd.DataFrame(report.items(), columns=["Feature", "OutlierCount"])

corr = df.select_dtypes(include=np.number).corr()
plt.figure(figsize=(10,8))
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Numeric Correlation Heatmap")
plt.show()

from scipy.stats import chi2_contingency

def cramers_v(x, y):
    table = pd.crosstab(x, y)
    chi2 = chi2_contingency(table)[0]
    n = table.sum().sum()
    r, k = table.shape
    return np.sqrt((chi2 / (n * (min(r-1, k-1)))))

sns.barplot(data=df, x="sex", y="survived")
plt.title("Survival Rate by Gender")
plt.show()

df["age_group"] = pd.cut(df["age"], bins=[0,12,18,35,60,100],
                         labels=["Child","Teen","YoungAdult","Adult","Senior"])

sns.barplot(data=df, x="age_group", y="survived")
plt.title("Survival by Age Group")
plt.show()

